# Site settings
title: Luoye Blog
SEOTitle: 落叶的博客 | Luoye Blog
header-img: img/post-bg-desk.jpg
email: qianzhiweisppc@gmail.com
description: "Every failure is leading towards success."
keyword: "Luoye, Luoye Blog, 落叶的博客, Luoye, 落叶, iOS, Apple, iPhone"
url: "http://qianzhiweisppc.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/qianzhiweisppc/qianzhiweisppc.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "做你自己，落叶飘零"
sidebar-avatar: /img/1111.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qianzhiweisppc
zhihu_username:     qianzhiweisppc
github_username:    qianzhiweisppc
facebook_username:  qianzhiweisppc
jianshu_username:   qianzhiweisppc
#twitter_username:   qianzhiweisppc




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: e156ac3f7f273a4d98f5                            #生成的clientID
  clientSecret: 534f2cae5eb77bd75ab3b79ee68c15d60fdf8685    #生成的clientSecret
  repo: qianzhiweisppc.github.io    #仓库名称
  owner: qianzhiweisppc    #github用户名
  admin: qianzhiweisppc
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-165597731-1'            # Format: UA-xxxxxx-xx
ga_domain: 19860320.xyz               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Github",
        href: "http://github.com"
    },{
        title: "简书",
        href: "http://www.jianshu.com"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
