repository: LY-Navi/LY-Navi
repository_url: https://github.com/qianzhiweisppc/qianzhiweisppc.github.io

timezone: Asia/Shanghai
lang: zh_CN

title: 落叶导航 · LY-Navi
alias_en: LY-Navi
alias_cn: 落叶导航
description: A Navigation Website for LY
keywords: 落叶导航, LY-Navi, LY, Navi, Navigation
url: https://19860320.xyz
established_at: "2016-10-01T00:00+08:00"

author: LuoYe
author_url: https://19860320.xyz

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
